name: peminjaman_alat
description: "A new Flutter project."

# Jangan publish ke pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Supabase
  supabase_flutter: ^2.5.6

  # File & image handling
  path: ^1.9.0
  image_picker_for_web: ^2.0.8
  image_picker: 1.1.2
  cached_network_image: ^3.3.1

  # UI helpers
  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.1
  provider: ^6.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/default.jpg
    - assets/images/ilustrasi_login.png
    - assets/images/logo_teknik_listrik.png

