name: peminjaman_alat
description: "A new Flutter project."

# Jangan publish ke pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.2.5  # sudah kamu tambahkan

  # Supabase
  supabase_flutter: ^1.0.8

  # Cupertino icons
  cupertino_icons: ^1.0.8

  # Tambahan untuk desktop image handling (pilihan)
  path: ^1.8.3
  image_picker_for_web: ^2.0.8 # kalau nanti mau support web
  fluttertoast: ^8.2.1 # untuk notifikasi toast jika mau
  provider: ^6.0.6 # optional, kalau mau state management

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/ilustrasi_login.png
    - assets/images/logo_teknik_listrik.png
    - assets/images/amperemtr.jpg
    - assets/images/pen.jpg
    - assets/images/power_meter.jpg
    - assets/images/voltmtr.jpg
    - assets/images/Oscilloscope.jpg
    - assets/images/multimeter.jpg
